skills_keywords = [
    "python", "java", "javascript", "c++", "c#", ".net", "ruby", "php",
    "html", "css", "javascript", "frontend development", "backend development",
    "full-stack development", "responsive design", "web services", "REST API",
    "sql", "database management", "data modeling", "data analysis", "big data",
    "data warehousing", "ETL", "NoSQL",
    "data structures", "algorithms", "algorithm design",
    "software development", "object-oriented programming", "functional programming",
    "frameworks", "software architecture", "design patterns", "code review",
    "code optimization", "software documentation",
    "devops", "docker", "kubernetes", "continuous integration", "CI/CD", "git", "Jenkins",
    "Ansible", "Terraform", "Infrastructure as Code (IaC)", "Continuous Delivery",
    "cloud computing", "AWS", "Azure", "Google Cloud", "Heroku", "AWS Lambda",
    "serverless", "cloud-native", "cloud security", "cloud architecture", "microservices",
    "testing", "automation", "software testing", "Junit", "Selenium", "test strategy",
    "TDD", "BDD", "functional testing", "load testing",
    "machine learning", "deep learning", "artificial intelligence",
    "natural language processing", "data mining", "computer vision",
    "algorithm design", "AI", "ML", "Kafka", "TensorFlow",
    "security", "penetration testing", "OWASP",
    "version control", "Git", "SVN",
    "agile methodology", "scrum", "Kanban",
    "leadership", "team building", "technology leadership", "interpersonal skills",
    "problem solving", "critical thinking", "debugging", "root cause analysis",
    "communication", "presentation", "technical writing", "Swagger", "API documentation",
    "collaboration", "teamwork", "cross-functional teams",
    "Linux/Unix", "bash scripting", "system administration", "AWS CLI",
    "networking", "stress management", "decision-making",
    "conflict resolution", "negotiation", "time management", "SCRUM Master",
    "software manager", "technology manager", "DevOps engineer", "Data Engineer",
    "IoT", "blockchain", "chatbots", "Microservice", "Distributed Systems",
    "software testing", "test automation", "unit testing", "integration testing",
    "real-time systems", "low-level programming", "RTOS", "embedded systems", "GPU programming",
    "concurrency", "distributed computing", "scalability", "performance tuning", "memory management",
    "network protocols", "backend architecture", "API design", "microservices architecture",
    "cloud-native", "serverless", "performance monitoring", "continuous delivery", "refactoring",
    "code quality", "code profiling", "dependency management", "software development lifecycle",
    "software design", "architecture patterns", "application security", "encryption",
    "authentication", "authorization", "web security", "vulnerability assessment",
    "secure coding practices", "SAST", "DAST", "agile project management", "sprint planning",
    "agile ceremonies", "sprint review", "sprint retrospective", "pair programming",
    "code collaboration tools", "code versioning tools", "continuous integration/continuous deployment",
    "software development methodologies", "technical debt management", "code reviews",
    "system design", "technical leadership", "coding standards", "software engineering best practices",
    "distributed version control", "architectural design principles", "software estimation",
    "software prototyping", "change management", "business process optimization",
    "root cause analysis", "problem management", "incident response", "release management",
    "Kubernetes", "Docker Swarm", "Continuous Deployment", "Site Reliability Engineering (SRE)",
    "Infrastructure Automation", "Container Orchestration", "Configuration Management",
    "Monitoring and Alerting", "Log Management", "Serverless Computing", "CICD Pipelines",
    "Load Balancing", "GitOps", "Cloud Cost Optimization",
    "AWS", "Azure", "Google Cloud", "Heroku", "Cloud Security", "Serverless Computing",
    "Cloud Architecture", "Microservices", "DevOps in the Cloud",
    "Neural Networks", "Deep Learning Frameworks", "Computer Vision Libraries", "NLP Libraries",
    "AI Model Training", "Model Deployment", "Machine Learning Pipelines", "AI/ML Ethics",
    "Team Building", "Team Leadership", "Team Collaboration", "Conflict Resolution",
    "Team Motivation", "Team Productivity", "Empowering Teams",
    "PostgreSQL",  # Add PostgreSQL
    "database administration",  # Add related keyword
    "SQL queries",  # Add related keyword
    "spring",  # Add Spring
    "spring boot",  # Add Spring Boot
    "MVC",  # Add MVC
]
